name: Go Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run Tests
      run: go test -v ./...
    - name: Send Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
        fields: repo,message,author,commit
        channel: ${{ env.DISCORD_GOECS_WEBHOOK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_GOECS_WEBHOOK: ${{ secrets.DISCORD_GOECS_WEBHOOK }}
