name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Tests
        run: go test -v ./...
      - name: Send Notification
        if: always()
        uses: technotechi/discord-notify-action@v1
        with:
          url: ${{ secrets.DISCORD_GOECS_WEBHOOK }}
          title: Go Test
          description: ${{ job.status }}
          author_name: ${{ github.actor }}
          author_icon: ${{ github.avatar_url }}
          fields: repo,message,author,commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
