name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Tests
        run: go test -v ./...
      - name: Send Notification
        if: always()
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ env.DISCORD_GOECS_WEBHOOK }}
          title: Go Ecs Test
          message: ${{ job.status }}
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GoEcs PR Test
        env:
          DISCORD_GOECS_WEBHOOK: ${{ secrets.DISCORD_GOECS_WEBHOOK }}
